version: "3.8"

services:
  web:
    build: .
    container_name: events-manager-web
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/events_manager
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379/0
      - SENDGRID_API_KEY=your_sendgrid_api_key
      - EMAIL_FROM=no-reply@miseventos.com
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your-email@example.com
      - SMTP_PASSWORD=your-email-password
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: events-manager-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events_manager
    ports:
      - "5433:5433"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: events-manager-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/events_manager
      - REDIS_URL=redis://redis:6379/0
      - SENDGRID_API_KEY=your_sendgrid_api_key
      - EMAIL_FROM=no-reply@events_manager.com
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your-email@example.com
      - SMTP_PASSWORD=your-email-password

  celery_beat:
    build: .
    command: celery -A app.celery_worker.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/events_manager
      - REDIS_URL=redis://redis:6379/0
      - SENDGRID_API_KEY=your_sendgrid_api_key
      - EMAIL_FROM=no-reply@events_manager.com
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your-email@example.com
      - SMTP_PASSWORD=your-email-password
