version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: events-manager-web
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/events_manager
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: events-manager-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events_manager
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: events-manager-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
