"""added fields to session

Revision ID: 3c08b976c3b2
Revises: 51f724d68537
Create Date: 2025-01-18 03:19:01.659100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c08b976c3b2'
down_revision: Union[str, None] = '51f724d68537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'capacity')
    # ### end Alembic commands ###
