"""init time and end time session

Revision ID: 51f724d68537
Revises: 15b7ea14248a
Create Date: 2025-01-18 03:05:34.852443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f724d68537'
down_revision: Union[str, None] = '15b7ea14248a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('session', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('session', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'date')
    op.drop_column('session', 'end_time')
    op.drop_column('session', 'start_time')
    # ### end Alembic commands ###
