"""added relation betwen attendee and session

Revision ID: ccb17dfcb039
Revises: 3c08b976c3b2
Create Date: 2025-01-21 22:22:47.736671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb17dfcb039'
down_revision: Union[str, None] = '3c08b976c3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendee', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendee', type_='foreignkey')
    op.drop_column('attendee', 'session_id')
    # ### end Alembic commands ###
