"""changed relation event speaker

Revision ID: f321c8a6b914
Revises: ccb17dfcb039
Create Date: 2025-01-21 22:36:26.440715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f321c8a6b914'
down_revision: Union[str, None] = 'ccb17dfcb039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_speaker_id_fkey', 'session', type_='foreignkey')
    op.drop_column('session', 'speaker_id')
    op.add_column('speaker', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'speaker', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'speaker', type_='foreignkey')
    op.drop_column('speaker', 'session_id')
    op.add_column('session', sa.Column('speaker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('session_speaker_id_fkey', 'session', 'speaker', ['speaker_id'], ['id'])
    # ### end Alembic commands ###
